name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -p 53412 debian@51.210.101.89 << 'EOF'
        # Ensure Node.js and npm are installed
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g pm2
        
        # Navigate to project directory
        cd /var/www/html/todolist
        
        # Stash local changes if any
        git stash --include-untracked || true
        git pull origin main
        
        # Install dependencies and build
        npm install
        npm run build
        
        # Restart the app with pm2
        pm2 restart index
        EOF